### ISSUE TITLE
Consider using full Docker image

### ISSUE THREAD

**Issue by LandonSchropp** [actions/npm#8]
It looks like the `npm` action uses `node:10-slim` as its tag in the Dockerfile. For many applications, this works fine. However, [Lerna](https://github.com/lerna/lerna) requires Git to be installed in order to run its publish command. I would imagine many people using this action are doing so with the intent of deploying an NPM package.

Would you consider using the full `10` tag instead of `10-slim`?

**Comment by vmosyaykin** [comment]
+1
git repos may also be used in package.json dependencies, and things like node-sass may require build tools in post-install scripts.

**Comment by LandonSchropp** [comment]
@sweetpalma I worked around this one by using the full `node` Docker image like this:

```
action "Build" {
  uses = "docker://node:10"
  runs = "yarn"
  args = "install"
}
```

Both NPM and Yarn are installed in this image.

**Comment by sweetpalma** [comment]
@LandonSchropp yes, that worked. Thanks.

**Comment by sweetpalma** [comment]
I've created a PR, probably it would work:
https://github.com/actions/npm/pull/14

**Comment by byCedric** [comment]
I'm also running into the missing git issue with Expo. Like said before, NPM allows developers to use a Git reference. Because of this, I think Git should exist within the environment of this action.

I did some searching around, and I found some interesting discussions related to our issue. 
- [This issue](https://github.com/nodejs/docker-node/pull/367) offers some good insight into why Git doesn't exist in node:10-alpine for example. 
- [Another discussion](https://github.com/nodejs/docker-node/issues/860) focuses on missing python for node-gyp. 

The argument I keep reading against adding Git and other tools are the image size. I can get into the part that this should be as small as possible for a widely used node image. But I'm not sure if the same argument applies to this action. As far as I can tell, this action should only be used by the workflow and not as a base image right?

**Comment by dustinsoftware** [comment]
I'm very curious why `node:10-slim` is preferred here instead of `node:10` if they have very similar build times running pulling and running scripts inside the containers. Maybe having a slim and non-slim variation in the UI would help alleviate confusion for others who are trying out actions and need the extra binaries, if for some reason the non-slim version can't be used as the base container.

**Comment by hfaulds** [comment]
Closing now https://github.com/actions/npm/pull/14 is merged
